[package]
name = "p2p-chat-blockchain"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0 
[profile.release]
opt-level = 3 

[dependencies]
md5 = "0.8.0"
rand = "0.9.1"
chrono = "0.4.41"
colored = "3.0.0" 

[[bin]]
name = "p2p_chat_blockchain"
path = "src/main.rs"
